// bins/torii-tokens/client/apps/react/src/components/TokenPanel.tsx
import {
  formatTimestamp,
  truncateAddress,
} from "@torii-tokens/shared";

interface Stats {
  totalTransfers: number;
  totalApprovals?: number;
  uniqueTokens: number;
  uniqueAccounts: number;
}

interface Transfer {
  id: string;
  token: string;
  from: string;
  to: string;
  amount?: string;
  tokenId?: string;
  blockNumber: number;
  timestamp: number;
}

interface TokenPanelProps {
  title: string;
  tokenType: "erc20" | "erc721" | "erc1155";
  stats: Stats | null;
  transfers: Transfer[];
  showAmount: boolean;
}

export default function TokenPanel({
  title,
  tokenType,
  stats,
  transfers,
  showAmount,
}: TokenPanelProps) {
  return (
    <section className={`panel token-panel ${tokenType}`}>
      <h2>{title}</h2>

      {stats && (
        <div className="status-grid" style={{ marginBottom: "1rem" }}>
          <div className="stat">
            <div className="stat-label">Transfers</div>
            <div className="stat-value">{stats.totalTransfers}</div>
          </div>
          {stats.totalApprovals !== undefined && (
            <div className="stat">
              <div className="stat-label">Approvals</div>
              <div className="stat-value">{stats.totalApprovals}</div>
            </div>
          )}
          <div className="stat">
            <div className="stat-label">
              {tokenType === "erc721" ? "Collections" : "Tokens"}
            </div>
            <div className="stat-value">{stats.uniqueTokens}</div>
          </div>
          <div className="stat">
            <div className="stat-label">
              {tokenType === "erc721" ? "Owners" : "Accounts"}
            </div>
            <div className="stat-value">{stats.uniqueAccounts}</div>
          </div>
        </div>
      )}

      {transfers.length === 0 ? (
        <div className="empty-state">No transfers yet</div>
      ) : (
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>From</th>
                <th>To</th>
                <th>{showAmount ? "Amount" : "Token ID"}</th>
                <th>Block</th>
                <th>Time</th>
              </tr>
            </thead>
            <tbody>
              {transfers.map((t) => (
                <tr key={t.id}>
                  <td className="address">{truncateAddress(t.from)}</td>
                  <td className="address">{truncateAddress(t.to)}</td>
                  <td className="amount">
                    {showAmount ? t.amount : t.tokenId}
                  </td>
                  <td>{t.blockNumber}</td>
                  <td className="timestamp">{formatTimestamp(t.timestamp)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </section>
  );
}

// bins/torii-tokens/client/apps/svelte/src/components/TokenPanel.svelte
<script lang="ts">
  import {
    formatTimestamp,
    truncateAddress,
  } from "@torii-tokens/shared";

  interface Stats {
    totalTransfers: number;
    totalApprovals?: number;
    uniqueTokens: number;
    uniqueAccounts: number;
  }

  interface Transfer {
    id: string;
    token: string;
    from: string;
    to: string;
    amount?: string;
    tokenId?: string;
    blockNumber: number;
    timestamp: number;
  }

  interface Props {
    title: string;
    tokenType: "erc20" | "erc721" | "erc1155";
    stats: Stats | null;
    transfers: Transfer[];
    showAmount: boolean;
  }

  let { title, tokenType, stats, transfers, showAmount }: Props = $props();
</script>

<section class="panel token-panel {tokenType}">
  <h2>{title}</h2>

  {#if stats}
    <div class="status-grid" style="margin-bottom: 1rem;">
      <div class="stat">
        <div class="stat-label">Transfers</div>
        <div class="stat-value">{stats.totalTransfers}</div>
      </div>
      {#if stats.totalApprovals !== undefined}
        <div class="stat">
          <div class="stat-label">Approvals</div>
          <div class="stat-value">{stats.totalApprovals}</div>
        </div>
      {/if}
      <div class="stat">
        <div class="stat-label">{tokenType === "erc721" ? "Collections" : "Tokens"}</div>
        <div class="stat-value">{stats.uniqueTokens}</div>
      </div>
      <div class="stat">
        <div class="stat-label">{tokenType === "erc721" ? "Owners" : "Accounts"}</div>
        <div class="stat-value">{stats.uniqueAccounts}</div>
      </div>
    </div>
  {/if}

  {#if transfers.length === 0}
    <div class="empty-state">No transfers yet</div>
  {:else}
    <div class="table-container">
      <table>
        <thead>
          <tr>
            <th>From</th>
            <th>To</th>
            <th>{showAmount ? "Amount" : "Token ID"}</th>
            <th>Block</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody>
          {#each transfers as t (t.id)}
            <tr>
              <td class="address">{truncateAddress(t.from)}</td>
              <td class="address">{truncateAddress(t.to)}</td>
              <td class="amount">{showAmount ? t.amount : t.tokenId}</td>
              <td>{t.blockNumber}</td>
              <td class="timestamp">{formatTimestamp(t.timestamp)}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</section>
